import { ArrowRight, Bell, Camera, Car, Clock, ConciergeBell, Leaf, Mail, MapPin, MessageCircle, Navigation, Phone, Send, ShieldCheck, Shirt, Users, Utensils, Wifi } from "lucide-react";
import { CheckCircle2 } from "lucide-react";
import Image from "next/image";

import { createContactMessageAction } from "@/app/(public)/contacto/actions";
import { PageHero } from "@/components/layout/page-hero";
import { SectionHeading } from "@/components/layout/section-heading";
import { TourismMapDynamic } from "@/components/maps/tourism-map-dynamic";
import { ReservationWizard } from "@/components/reservations/reservation-wizard";
import { Button, LinkButton } from "@/components/ui/button";
import { RoomCard } from "@/components/ui/room-card";
import { ServiceCard } from "@/components/ui/service-card";
import type { Locale } from "@/i18n/config";
import type { Dictionary } from "@/i18n/get-dictionary";
import { pathFor } from "@/i18n/routing";
import { destinationsRepository } from "@/lib/repositories/destinations-repository";
import { getRooms } from "@/lib/repositories/hotel-repository";
import { roomsRepository } from "@/lib/repositories/rooms-repository";
import { servicesRepository } from "@/lib/repositories/services-repository";
import { settingsRepository } from "@/lib/repositories/settings-repository";
import { siteConfig } from "@/lib/site";

type PageContext = { locale: Locale; dictionary: Dictionary };

const heroImages = {
  home: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=2200&q=88", "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=2200&q=88", "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=2200&q=88", "https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=2200&q=88"],
  rooms: ["https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=2200&q=88", "https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=2200&q=88", "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=2200&q=88", "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=2200&q=88"],
  services: ["https://images.unsplash.com/photo-1601919051950-bb9f3ffb3fee?auto=format&fit=crop&w=2200&q=88", "https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=2200&q=88", "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=2200&q=88", "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=2200&q=88"],
  surroundings: ["https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=2200&q=88", "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=2200&q=88", "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=2200&q=88", "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?auto=format&fit=crop&w=2200&q=88"],
  contact: ["https://images.unsplash.com/photo-1601919051950-bb9f3ffb3fee?auto=format&fit=crop&w=2200&q=88", "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=2200&q=88", "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?auto=format&fit=crop&w=2200&q=88", "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=2200&q=88"],
};

export async function HomePublicPage({ locale, dictionary }: PageContext) {
  const [rooms, destinations, services, settings] = await Promise.all([roomsRepository.getAll(locale), destinationsRepository.getAll(locale), servicesRepository.getAll(locale), settingsRepository.get(locale)]);
  const t = dictionary.home; const icons = [Leaf, ShieldCheck, Wifi, Car, Utensils, Bell];
  return <main><PageHero bookingRooms={rooms} description={settings?.slogan ?? t.description} dictionary={dictionary} eyebrow={t.eyebrow} images={heroImages.home} locale={locale} showActions title={t.title} />
    <section className="border-b border-hotel-line bg-hotel-ivory py-10"><div className="hotel-container grid gap-6 md:grid-cols-3 lg:grid-cols-6">{services.slice(0, 6).map((service, index) => { const Icon = icons[index] ?? ShieldCheck; return <div className="flex items-center gap-3 md:border-r md:border-hotel-line md:pr-4" key={service.slug}><Icon className="size-8 shrink-0 text-hotel-forest" /><div><h3 className="text-xs font-bold uppercase text-hotel-forest">{service.title}</h3><p className="mt-1 text-xs leading-5 text-hotel-muted">{t.serviceDetail}</p></div></div>; })}{!services.length ? <p className="text-sm text-hotel-muted lg:col-span-6">{t.servicesUnavailable}</p> : null}</div></section>
    <section className="py-14 md:py-16" id="turismo"><div className="hotel-container grid gap-9 lg:grid-cols-[0.55fr_1.45fr] lg:items-start xl:grid-cols-[0.62fr_1.38fr]"><div><p className="mb-3 text-xs font-bold uppercase tracking-[0.24em] text-hotel-gold-700">{t.discover}</p><h2 className="hotel-serif text-4xl font-bold leading-tight text-hotel-forest md:text-5xl">{t.destinationsTitle}</h2><p className="mt-5 leading-8 text-hotel-muted">{t.destinationsDescription}</p><LinkButton className="mt-7" href={`${pathFor(locale, "surroundings")}#turismo`} variant="forest">{t.exploreAll} <ArrowRight className="size-4" /></LinkButton></div><TourismMapDynamic destinations={destinations} dictionary={dictionary} locale={locale} /></div></section>
    <section className="bg-hotel-ivory py-16"><div className="hotel-container"><div className="mb-8 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><SectionHeading align="left" eyebrow={t.roomsEyebrow} title={t.roomsTitle} /><LinkButton href={pathFor(locale, "rooms")} variant="outline">{t.viewAllRooms} <ArrowRight className="size-4" /></LinkButton></div>{rooms.length ? <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{rooms.map((room) => <RoomCard dictionary={dictionary} key={room.id} locale={locale} room={room} />)}</div> : <p className="rounded-[8px] border border-hotel-line bg-white p-6 text-center text-sm text-hotel-muted">{t.roomsUnavailable}</p>}</div></section>
    <section className="hotel-dark-gradient text-white"><div className="hotel-container grid gap-8 py-12 lg:grid-cols-[1fr_1fr] lg:items-center"><div><h2 className="hotel-serif text-4xl font-bold leading-tight md:text-5xl">{t.ctaTitle}</h2><p className="mt-4 text-white/80">{t.ctaDescription}</p></div><div className="flex justify-start lg:justify-end"><LinkButton href={pathFor(locale, "book")} variant="gold">{dictionary.common.bookNow}</LinkButton></div></div></section>
  </main>;
}

export async function RoomsPublicPage({ locale, dictionary }: PageContext) {
  const rooms = await roomsRepository.getAll(locale); const t = dictionary.rooms;
  const targets = ["#habitaciones", "#habitacion-ejecutiva", "#habitacion-doble", "#suite-premium", "#suite-familiar"];
  return <main><PageHero active={dictionary.navbar.rooms} bookingRooms={rooms} description={t.description} dictionary={dictionary} eyebrow={t.eyebrow} images={heroImages.rooms} locale={locale} showWeather={false} title={t.title} /><section className="scroll-mt-28 py-16" id="habitaciones"><div className="hotel-container"><SectionHeading eyebrow={t.sectionEyebrow} title={t.sectionTitle} /><nav aria-label={t.filterLabel} className="my-9 flex flex-wrap justify-center gap-2">{t.filters.map((label, index) => <a className={`inline-flex min-h-11 items-center rounded-[999px] px-6 py-2 text-xs font-bold uppercase transition hover:-translate-y-0.5 ${index === 0 ? "bg-hotel-forest text-white" : "border border-hotel-line bg-white text-hotel-forest hover:border-hotel-gold"}`} href={targets[index]} key={targets[index]}>{label}</a>)}</nav>{rooms.length ? <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">{rooms.map((room) => <div className="scroll-mt-28" id={room.slug} key={room.id}><RoomCard dictionary={dictionary} locale={locale} room={room} /></div>)}</div> : <p className="rounded-[8px] border border-hotel-line bg-hotel-ivory p-6 text-center text-sm text-hotel-muted">{t.unavailable}</p>}</div></section><section className="hotel-dark-gradient py-14 text-white"><div className="hotel-container flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><h2 className="hotel-serif text-4xl font-bold">{t.cta}</h2><LinkButton href={pathFor(locale, "book")} variant="gold">{dictionary.common.bookNow}</LinkButton></div></section></main>;
}

export async function ServicesPublicPage({ locale, dictionary }: PageContext) {
  const [services, rooms] = await Promise.all([servicesRepository.getAll(locale), roomsRepository.getAll(locale)]); const t = dictionary.services; const extraIcons = [Wifi, ShieldCheck, Bell, Shirt, ConciergeBell];
  return <main><PageHero active={dictionary.navbar.services} bookingRooms={rooms} description={t.description} dictionary={dictionary} eyebrow={t.eyebrow} images={heroImages.services} locale={locale} title={t.title} /><section className="py-16"><div className="hotel-container"><SectionHeading description={t.sectionDescription} eyebrow={t.eyebrow} title={t.sectionTitle} />{services.length ? <div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{services.map((service) => <ServiceCard dictionary={dictionary} key={service.id} locale={locale} service={service} />)}</div> : <p className="mt-10 rounded-[8px] border border-hotel-line bg-hotel-ivory p-6 text-center text-sm text-hotel-muted">{t.unavailable}</p>}<div className="mt-10 grid gap-4 rounded-[8px] border border-hotel-line bg-hotel-ivory p-6 shadow-hotel-soft md:grid-cols-2 lg:grid-cols-5">{t.extras.map((label, index) => { const Icon = extraIcons[index]; return <div className="flex gap-3 lg:border-r lg:border-hotel-line lg:pr-4" key={label}><Icon className="size-8 shrink-0 text-hotel-forest" /><div><h3 className="text-sm font-bold text-hotel-forest">{label}</h3><p className="mt-1 text-xs leading-5 text-hotel-muted">{t.available}</p></div></div>; })}</div></div></section><section className="hotel-dark-gradient py-14 text-white"><div className="hotel-container flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><h2 className="hotel-serif text-4xl font-bold">{t.cta}</h2><LinkButton href={pathFor(locale, "book")} variant="gold">{dictionary.common.bookNow}</LinkButton></div></section></main>;
}

export async function SurroundingsPublicPage({ locale, dictionary }: PageContext) {
  const [destinations, rooms] = await Promise.all([destinationsRepository.getAll(locale), roomsRepository.getAll(locale)]); const t = dictionary.surroundings; const benefitIcons = [MapPin, Leaf, Camera, Users];
  const routeUrl = (latitude: number, longitude: number) => `https://www.google.com/maps/dir/?api=1&origin=${siteConfig.coordinates.lat},${siteConfig.coordinates.lng}&destination=${latitude},${longitude}`;
  return <main><PageHero active={t.navLabel} bookingRooms={rooms} description={t.description} dictionary={dictionary} eyebrow={t.eyebrow} images={heroImages.surroundings} locale={locale} title={t.title} /><section className="py-16" id="turismo"><div className="hotel-container grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><SectionHeading align="left" description={t.sectionDescription} eyebrow={t.eyebrow} title={t.sectionTitle} /><div className="grid gap-5 sm:grid-cols-2 md:grid-cols-4">{t.benefits.map(([title, text], index) => { const Icon = benefitIcons[index]; return <div className="border-hotel-line text-center md:border-r md:px-4" key={title}><div className="mx-auto grid size-16 place-items-center rounded-full bg-hotel-sage text-hotel-forest"><Icon className="size-8" /></div><h3 className="mt-4 text-sm font-bold text-hotel-forest">{title}</h3><p className="mt-2 text-xs leading-6 text-hotel-muted">{text}</p></div>; })}</div></div></section><section className="bg-hotel-ivory py-16" id="atracciones"><div className="hotel-container"><SectionHeading align="left" description={t.exploreDescription} eyebrow={t.featured} title={t.exploreTitle} /><div className="mt-8 scroll-mt-28" id="mapa"><TourismMapDynamic destinations={destinations} dictionary={dictionary} locale={locale} /></div>{destinations.length ? <div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{destinations.map((destination) => <article className="overflow-hidden rounded-[8px] border border-hotel-line bg-white shadow-hotel-soft transition duration-300 hover:-translate-y-1 hover:shadow-hotel-card" key={destination.id}><Image alt={destination.title} className="h-44 w-full object-cover" height={220} src={destination.image} width={420} /><div className="p-5"><p className="text-xs font-bold uppercase tracking-[0.18em] text-hotel-gold-700">{t.touristDestination}</p><h3 className="hotel-serif mt-1 text-2xl font-bold text-hotel-forest">{destination.title}</h3><p className="mt-3 line-clamp-3 text-sm leading-7 text-hotel-muted">{destination.description}</p><div className="mt-4 flex justify-between gap-4 text-sm text-hotel-forest"><strong>{destination.estimatedDistance}</strong><strong>{destination.estimatedTime}</strong></div><div className="mt-5 grid gap-2 sm:grid-cols-2"><LinkButton href="#mapa" variant="outlineDark">{dictionary.common.viewDetails}</LinkButton><a className="inline-flex min-h-12 items-center justify-center gap-2 rounded-[6px] bg-hotel-forest px-4 py-3 text-center text-sm font-bold uppercase text-white transition hover:bg-hotel-forest-800" href={routeUrl(destination.latitude, destination.longitude)} rel="noopener noreferrer" target="_blank">{t.route} <Navigation className="size-4" /></a></div></div></article>)}</div> : <p className="mt-10 rounded-[8px] border border-hotel-line bg-white p-6 text-center text-sm text-hotel-muted">{t.unavailable}</p>}</div></section></main>;
}

export async function ContactPublicPage({ locale, dictionary }: PageContext) {
  const [settings, destinations, rooms] = await Promise.all([settingsRepository.get(locale), destinationsRepository.getAll(locale), roomsRepository.getAll(locale)]); const t = dictionary.contact;
  const items = [{ label: t.location, value: settings?.address ?? siteConfig.address, icon: MapPin }, { label: t.phone, value: settings?.phone ?? siteConfig.phone, icon: Phone }, { label: t.email, value: settings?.email ?? siteConfig.email, icon: Mail }, { label: "WhatsApp", value: settings?.whatsapp ?? siteConfig.whatsapp, icon: MessageCircle }, { label: t.hours, value: `Check-in: ${settings?.checkInTime ?? siteConfig.checkIn} · Check-out: ${settings?.checkOutTime ?? siteConfig.checkOut}`, icon: Clock }];
  return <main><PageHero active={dictionary.navbar.contact} bookingRooms={rooms} description={t.description} dictionary={dictionary} eyebrow={t.eyebrow} images={heroImages.contact} locale={locale} showWeather={false} title={t.title} /><section className="py-14 md:py-16"><div className="hotel-container"><SectionHeading description={t.sectionDescription} eyebrow={t.sectionEyebrow} title={t.sectionTitle} /><div className="mt-10 grid items-start gap-7 lg:grid-cols-[0.72fr_1.18fr] xl:grid-cols-[0.68fr_1.08fr_0.9fr]"><aside className="space-y-5"><h2 className="hotel-serif text-3xl font-bold text-hotel-forest">{t.information}</h2>{items.map((item) => <div className="flex gap-4" key={item.label}><div className="grid size-14 shrink-0 place-items-center rounded-[8px] bg-hotel-forest text-hotel-gold"><item.icon className="size-6" /></div><div><h3 className="font-bold text-hotel-forest">{item.label}</h3><p className="mt-1 text-sm leading-6 text-hotel-muted">{item.value}</p></div></div>)}</aside><form action={createContactMessageAction} className="rounded-[8px] border border-hotel-line bg-hotel-ivory p-6 shadow-hotel-soft"><input name="locale" type="hidden" value={locale} /><h2 className="hotel-serif mb-5 text-3xl font-bold text-hotel-forest">{t.sendTitle}</h2><div className="grid gap-4 md:grid-cols-2"><ContactInput label={t.fullName} name="name" placeholder={t.namePlaceholder} /><ContactInput label={t.email} name="email" placeholder={t.emailPlaceholder} /><ContactInput label={t.phone} name="phone" placeholder={t.phonePlaceholder} /><ContactInput label={t.subject} name="subject" placeholder={t.subjectPlaceholder} /></div><label className="mt-4 block text-sm font-medium text-hotel-ink">{t.message}<textarea className="mt-2 h-36 w-full rounded-[6px] border border-hotel-line bg-white p-3 outline-none transition focus:border-hotel-gold" name="message" placeholder={t.messagePlaceholder} required /></label><Button className="mt-5 w-full" type="submit" variant="forest">{t.send} <Send className="size-4" /></Button></form><aside className="scroll-mt-28 lg:col-span-2 xl:col-span-1" id="mapa"><TourismMapDynamic compact destinations={destinations.slice(0, 2)} dictionary={dictionary} locale={locale} /><LinkButton className="mt-4 w-full" href={`${pathFor(locale, "surroundings")}#turismo`} variant="outlineDark">{t.explore}</LinkButton></aside></div></div></section></main>;
}

function ContactInput({ label, placeholder, name }: { label: string; placeholder: string; name: string }) { return <label className="text-sm font-medium text-hotel-ink">{label}<input autoComplete={name === "name" ? "name" : name === "email" ? "email" : name === "phone" ? "tel" : undefined} className="mt-2 h-12 w-full rounded-[6px] border border-hotel-line bg-white px-3 outline-none transition focus:border-hotel-gold" name={name} placeholder={placeholder} required={name !== "phone"} type={name === "email" ? "email" : name === "phone" ? "tel" : "text"} /></label>; }

export async function BookingPublicPage({ locale, dictionary, searchParams }: PageContext & { searchParams: Record<string, string | string[] | undefined> }) {
  const rooms = await getRooms(locale); const room = typeof searchParams.room === "string" ? searchParams.room : undefined; const initialRoomId = rooms.some((item) => item.id === room) ? room : rooms[0]?.id; const t = dictionary.booking;
  const stringParam = (key: string) => typeof searchParams[key] === "string" ? searchParams[key] as string : undefined;
  return <main className="bg-hotel-cream"><section className="border-b border-hotel-line bg-hotel-ivory py-12 md:py-16"><div className="hotel-container"><p className="text-xs font-bold uppercase tracking-[0.24em] text-hotel-gold-700">{t.eyebrow}</p><h1 className="hotel-serif mt-3 text-5xl font-bold text-hotel-forest md:text-6xl">{t.title}</h1><p className="mt-3 max-w-2xl leading-7 text-hotel-muted">{t.description}</p></div></section><ReservationWizard dictionary={dictionary} error={stringParam("error")} initialAdults={Number(stringParam("adults")) || 2} initialCheckIn={stringParam("checkIn")} initialCheckOut={stringParam("checkOut")} initialChildren={Number(stringParam("children")) || 0} initialRoomId={initialRoomId} locale={locale} rooms={rooms} /></main>;
}

export function ConfirmationPublicPage({ locale, dictionary }: PageContext) {
  const t = dictionary.confirmation;
  return <main className="grid min-h-[70vh] place-items-center px-6 py-16"><section className="max-w-2xl rounded-[8px] border border-hotel-line bg-hotel-ivory p-8 text-center shadow-hotel-card"><CheckCircle2 className="mx-auto size-16 text-hotel-forest" /><p className="mt-6 text-xs font-bold uppercase tracking-[0.24em] text-hotel-gold-700">{t.eyebrow}</p><h1 className="hotel-serif mt-3 text-4xl font-bold text-hotel-forest md:text-5xl">{t.title}</h1><p className="mt-4 leading-8 text-hotel-muted">{t.description}</p><p className="mt-4 rounded-[8px] bg-hotel-sage/60 px-4 py-3 text-sm font-semibold text-hotel-forest">{t.notice}</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><LinkButton href={pathFor(locale, "home")} variant="forest">{t.home}</LinkButton><LinkButton href={pathFor(locale, "contact")} variant="outline">{t.contact}</LinkButton></div></section></main>;
}
