import type { Dictionary } from "./es";

const en = {
  common: { hotelName: "Hotel Casa Blanca", bookNow: "Book now", learnMore: "Learn more", viewDetails: "View details", unavailable: "Content is currently unavailable.", adults: "Adults", children: "Children", guests: "Guests", beds: "Beds", night: "night", nights: "nights", loading: "Loading..." },
  navbar: { primaryNavigation: "Main navigation", home: "Home", rooms: "Rooms", services: "Services", surroundings: "Explore", contact: "Contact", tourism: "Tourism", interactiveMap: "Interactive map", nearbyAttractions: "Nearby attractions", directions: "Directions", openMenu: "Open menu", closeMenu: "Close menu", selectLanguage: "Select language", languageMenu: "Languages", spanish: "Español", english: "English" },
  home: { eyebrow: "Exclusivity & Nature", title: "Your oasis of rest in El Progreso, Yoro", description: "Nature, comfort, and hospitality in perfect harmony.", serviceDetail: "Warm, attentive service in every detail.", servicesUnavailable: "Our services are currently unavailable.", discover: "Discover Honduras", destinationsTitle: "Explore destinations near us", destinationsDescription: "Connect with Honduras’s leading attractions. Select a destination to see its distance and estimated travel time from the hotel.", exploreAll: "Explore all destinations", roomsEyebrow: "Our rooms", roomsTitle: "Rest for every occasion", viewAllRooms: "View all rooms", roomsUnavailable: "Our rooms are currently unavailable.", ctaTitle: "Enjoy an experience that restores body and soul", ctaDescription: "Book directly with us for our best available benefits and guaranteed rates." },
  rooms: { eyebrow: "Rooms & Suites", title: "Rest for every occasion", description: "Spaces designed for your comfort, surrounded by nature and equipped with everything you need.", sectionEyebrow: "Our rooms", sectionTitle: "Choose your ideal space", filterLabel: "Jump to a room type", filters: ["All", "Executive", "Double", "Suites", "Family"], unavailable: "Our rooms are currently unavailable.", cta: "Enjoy a one-of-a-kind stay at Hotel Casa Blanca", perNight: "per night", details: "View details", book: "Book" },
  services: { eyebrow: "Our services", title: "Everything you need for a perfect stay", description: "Enjoy facilities designed for comfort, business, relaxation, and memorable experiences.", sectionTitle: "Comfort, well-being, and memorable experiences", sectionDescription: "Discover everything Hotel Casa Blanca has to offer.", unavailable: "Our services are currently unavailable.", available: "Available to hotel guests.", extras: ["High-speed Wi-Fi", "24/7 Security", "Personalized service", "Laundry service", "Room service"], cta: "Enjoy a one-of-a-kind stay at Hotel Casa Blanca", more: "Learn more" },
  surroundings: { navLabel: "Surroundings", eyebrow: "Our surroundings", title: "Nature, culture, and adventure await", description: "Discover El Progreso, Yoro, and the beauty beyond it—a destination filled with experiences for every kind of traveler.", sectionTitle: "A privileged setting in the heart of Yoro", sectionDescription: "Hotel Casa Blanca is strategically located in El Progreso, Yoro, surrounded by nature, history, and attractions that make every stay memorable.", benefits: [["A strategic location", "Minutes from downtown El Progreso, with convenient access to major roads."], ["Abundant nature", "Mountains, rivers, and natural scenery invite you to slow down and recharge."], ["Nearby attractions", "Beaches, parks, historic sites, and charming towns are all within reach."], ["Culture and tradition", "Experience the warmth of our people and Yoro’s rich cultural heritage."]], featured: "Featured destinations", exploreTitle: "Explore the best of Honduras", exploreDescription: "From Caribbean beaches to remarkable historic sites and natural wonders.", touristDestination: "Tourist destination", route: "View route", unavailable: "Destinations are currently unavailable." },
  contact: { eyebrow: "Contact us", title: "We are here for you", description: "It will be our pleasure to help you plan an unforgettable stay at Hotel Casa Blanca.", sectionEyebrow: "Contact", sectionTitle: "Get in touch", sectionDescription: "We are ready to assist with questions, reservations, or special requests.", information: "Contact information", location: "Location", phone: "Phone", email: "Email address", hours: "Opening hours", sendTitle: "Send us a message", fullName: "Full name", namePlaceholder: "Your name", emailPlaceholder: "Your email", phonePlaceholder: "Your phone number", subject: "Subject", subjectPlaceholder: "How can we help you?", message: "Message", messagePlaceholder: "Write your message here...", send: "Send message", explore: "Explore all destinations" },
  bookingBar: { checkIn: "Check-in", checkOut: "Check-out", adults: "Adults", children: "Children", room: "Room", search: "Check availability", searching: "Searching...", invalidDates: "Please select a check-out date after check-in.", decrease: "Decrease", increase: "Increase" },
  booking: { eyebrow: "Booking", title: "Complete your reservation request", description: "Review your stay and submit your request. Our team will confirm availability before sending a payment link.", steps: ["Dates", "Rooms", "Guest information", "Confirmation"], ready: "Ready to continue?", pendingNotice: "Your request will remain pending while the hotel reviews it.", back: "Back", submit: "Send request", continue: "Continue", noRooms: "No rooms are currently available for reservation requests.", datesTitle: "Select your dates", datesHelp: "Choose check-in first, followed by check-out.", selectDates: "Select dates", room: "Room", checking: "Checking...", checkAvailability: "Check availability", available: "This room is available for the selected dates.", unavailable: "This room is not available for the selected dates.", alternatives: "Available alternatives:", previousMonth: "Previous month", nextMonth: "Next month", calendar: "Calendar", weekdays: ["M", "T", "W", "T", "F", "S", "S"], chooseRoom: "Select a room", guestInfo: "Guest information", fullName: "Full name", namePlaceholder: "e.g. Jane Smith", email: "Email address", phone: "Phone", country: "Country of residence", documentNumber: "Document number", documentType: "Document type", address: "Address", addressPlaceholder: "e.g. Palmira, San Pedro Sula", notes: "Notes or special requests", notesPlaceholder: "Tell us about any special requests for your stay...", contactMethod: "Preferred contact method", contactMethods: ["WhatsApp", "Email", "Phone call"], additionalInfo: "Additional information", terms: "I accept the Terms & Conditions and Privacy Policy.", data: "I authorize Hotel Casa Blanca to process my information for this reservation.", summary: "Your reservation summary", stay: "Stay", plan: "Plan", lodgingOnly: "Room only", nightlyRate: "Nightly rate", taxes: "Taxes and fees", total: "Total", secure: "Secure booking. Your dates are held only after the hotel confirms payment.", select: "Select", validationError: "Please review the required information and try again.", availabilityError: "The room is no longer available for those dates. Please choose different dates or another room." },
  confirmation: { eyebrow: "Request received", title: "Thank you for contacting us", description: "Your request is pending review. The Hotel Casa Blanca team will check availability and contact you with the next step.", notice: "The room is not held until the hotel confirms payment.", home: "Back to home", contact: "Contact the hotel" },
  validation: { checkIn: "Please select a check-in date.", email: "Please enter a valid email address.", adult: "At least one adult is required." },
  footer: { quickLinks: "Quick links", services: "Services", contact: "Contact", hours: "Hours", rights: "All rights reserved.", terms: "Terms & Conditions", privacy: "Privacy Policy", unavailable: "Content is currently unavailable.", fallbackSlogan: "Your retreat in El Progreso, Yoro. Nature, comfort, and hospitality in perfect harmony." },
  map: { explore: "Explore nearby", nearby: "Near the hotel", destinations: "Destinations from the hotel", previous: "Previous destination", next: "Next destination", carousel: "Destination carousel", mapLabel: "Map showing the route from Hotel Casa Blanca to", distance: "Distance", estimatedTime: "Estimated time", route: "View route", calculating: "Calculating the driving route...", routeUnavailable: "The route is temporarily unavailable.", noDestinations: "No destinations are currently available.", loading: "Loading interactive map...", categories: { beach: "Beach", nature: "Nature", adventure: "Adventure", city: "City", culture: "Culture", destination: "Tourist destination" } },
  weather: { sunny: "Sunny", localTime: "Local time" },
  accessibility: { showImage: "Show image", previousImage: "Previous image", nextImage: "Next image", whatsapp: "Contact us on WhatsApp" },
  reservationStatuses: { pendingReview: "Pending review", awaitingPayment: "Awaiting payment", confirmed: "Confirmed", cancelled: "Cancelled", checkedIn: "Checked in", checkedOut: "Checked out" },
  seo: { homeTitle: "Hotel Casa Blanca | Hotel in El Progreso, Yoro", homeDescription: "Discover Hotel Casa Blanca in El Progreso, Yoro. Comfortable rooms, nature, services, and online reservation requests.", roomsTitle: "Rooms", roomsDescription: "Executive rooms, double rooms, and suites at Hotel Casa Blanca.", servicesTitle: "Services", servicesDescription: "Restaurant, pool, events, gym, gardens, and private parking.", surroundingsTitle: "Surroundings", surroundingsDescription: "Tourism, routes, and attractions near Hotel Casa Blanca in Yoro.", contactTitle: "Contact", contactDescription: "Contact Hotel Casa Blanca in El Progreso, Yoro.", bookTitle: "Book", bookDescription: "Request a stay at Hotel Casa Blanca. Your booking remains pending until reviewed.", confirmationTitle: "Request received", confirmationDescription: "Confirmation that your reservation request was received." },
} satisfies Dictionary;

export default en;
